# Generated by Django 5.1.6 on 2025-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateTimeField(auto_now_add=True)),
                ('updated_ed', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('imdb', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('genre', models.CharField(max_length=50)),
                ('actor', models.ManyToManyField(to='configapp.actor')),
            ],
        ),
    ]
